### ISSUE TITLE
ts files are missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [jordanpowell88/angular-ct#22]
I cloned the project and then I run npx cypress open I get the following error message. No changes were made to the files.

Some basic Git commands are:
```
PS D:\angular-ct> npx cypress open

i ´¢ówds´¢ú: Project is running at http://localhost:59526/webpack-dev-server/
i ´¢ówds´¢ú: webpack output is served from /__cypress/src
i ´¢ówds´¢ú: Content not from webpack is served from D:\angular-ct
├ù ´¢ówdm´¢ú: 19 assets
runtime modules 7 KiB 10 modules
modules with errors 663 bytes [errors]
  modules by path ./src/app/home/ 273 bytes 7 modules
  modules by path ./src/app/count/ 234 bytes 6 modules
  modules by path ./src/app/shared/ 78 bytes
    ./src/app/shared/footer/footer.component.cy.ts 39 bytes [built] [code generated] [1 error]
    ./src/app/shared/toolbar/toolbar.component.cy.ts 39 bytes [built] [code generated] [1 error]
  ./src/app/app.component.cy.ts 39 bytes [built] [code generated] [1 error]
  ./projects/angular/src/support/index.ts 39 bytes [built] [code generated] [1 error]
modules by path ./node_modules/@cypress/webpack-dev-server/dist/*.js 6.11 KiB
  ./node_modules/@cypress/webpack-dev-server/dist/browser.js 89 bytes [built] [code generated]
  ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 5.55 KiB [not cacheable] [built] [code generated]
  ./node_modules/@cypress/webpack-dev-server/dist/aut-runner.js 483 bytes [built] [code generated]
./cypress/support/component.js 45 bytes [built] [code generated]

ERROR in ./projects/angular/src/support/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\projects\angular\src\support\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./cypress/support/component.js 1:0-43
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 2:30-86
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/app.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\app.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 5:16-100
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/count/count.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\count\count.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 9:16-108
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/count/ngrx-counter/ngrx-counter.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\count\ngrx-counter\ngrx-counter.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 17:16-128
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/count/observables/observables.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\count\observables\observables.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 21:16-126
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/count/overrides/overrides.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\count\overrides\overrides.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 25:16-122
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/count/parent/parent.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\count\parent\parent.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 29:16-116
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/count/test-output-button/test-output-button.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\count\test-output-button\test-output-button.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 33:16-140
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/home/card/card.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\home\card\card.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 37:16-111
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/home/home.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\home\home.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 13:16-106
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/home/next-steps/next-steps.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\home\next-steps\next-steps.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 41:16-123
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/home/resources/resources.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\home\resources\resources.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 45:16-122
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/home/rocket/rocket.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\home\rocket\rocket.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 49:16-116
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/home/round-card-buttons/round-card-buttons.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\home\round-card-buttons\round-card-buttons.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 53:16-140
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/home/svg/svg.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\home\svg\svg.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 57:16-110
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/shared/footer/footer.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\shared\footer\footer.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 61:16-118
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in ./src/app/shared/toolbar/toolbar.component.cy.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\angular-ct\src\app\shared\toolbar\toolbar.component.cy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at D:\angular-ct\node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js 65:16-120
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:4-41

ERROR in error TS6053: File 'D:angular-ct       sconfig.json' not found.

ERROR in error TS18003: No inputs were found in config file 'C:/Users/mail/AppData/Local/Temp/tmp-24228-i6RPX5It82ag/tsconfig.cy.json'. Specified 'include' paths were '["D:angular-ctsrc***.cy.ts"]' and 'exclude' paths were '["D:angular-ctout-tsccy"]'.

webpack 5.50.0 compiled with 19 errors in 2357 ms
i ´¢ówdm´¢ú: Failed to compile.
PS D:\angular-ct> 
```

**Comment by SoftwareDesign-Solution** [comment]
I ran git clone https://github.com/jordanpowell88/angular-ct.git, cd angular-ct and then npm ci 

Some basic Git commands are:
```
{
  "name": "angular-ct",
  "version": "0.0.1-beta.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@ngrx/store": "^12.5.1",
    "@ngrx/store-devtools": "^12.5.1",
    "rxjs": "~6.6.0",
    "tmp": "^0.2.1",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-builders/jest": "latest",
    "@angular-devkit/build-angular": "~12.2.16",
    "@angular/cli": "~12.2.16",
    "@angular/compiler-cli": "~12.2.0",
    "@briebug/jest-schematic": "^4.0.0",
    "@cypress/webpack-dev-server": "^1.8.2",
    "@types/babel__core": "^7.1.18",
    "@types/jest": "latest",
    "@types/node": "^12.11.1",
    "@types/tmp": "^0.2.3",
    "@types/webpack-dev-server": "^3.11.3",
    "babel-loader": "^8.2.3",
    "cypress": "https://cdn.cypress.io/beta/npm/10.0.0/darwin-x64/10.0-release-188b9a742ee2ef51102167bfd84b3696a3f72a26/cypress.tgz",
    "jest": "latest",
    "jest-preset-angular": "^11.1.1",
    "ng-packagr": "^12.1.1",
    "raw-loader": "^4.0.2",
    "typescript": "~4.3.5"
  }
}

```

**Comment by jordanpowell88** [comment]
Ok thanks for clarifying. Let me look into it

**Comment by jordanpowell88** [comment]
@SoftwareDesign-Solution I am unable to reproduce the issue you are describing.
